_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ["train"]
  TEST: ["val"]

MODEL:
  WEIGHTS: ""
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 300  # Per FPN level
    PRE_NMS_TOPK_TEST: 300  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 10
    POST_NMS_TOPK_TEST: 10
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 1
    NAME: "KRCNNConvDeconvUpsampleHead"
    MIN_KEYPOINTS_PER_IMAGE: 1
    POOLER_RESOLUTION: 14

SOLVER:
  STEPS: (15000, 15500)
  MAX_ITER: 15000
INPUT:
  RANDOM_FLIP: "none"
#MODEL.ROI_DENSEPOSE_HEAD.LOSS_NAME

